### ISSUE TITLE
Multiple Rules converging on single Consequent should combine, not overwrite

### ISSUE THREAD

**Issue by JDWarner** [scikit-fuzzy/scikit-fuzzy#108]
This affects systems where several Rules all name the same Consequent Term as output.

Currently, all Rules are evaluated individually and then those results are *directly written* to the appropriate Consequent Term. This results in prior results being overwritten. They should instead be combined using `np.fmax`.

I've confirmed this is the true issue underlying [two](https://groups.google.com/forum/#!topic/scikit-fuzzy/CpuOelf_O6U) recent [reports ](https://groups.google.com/forum/#!topic/scikit-fuzzy/0ffHDqEVBxM)on the mailing list.

The necessary fix is pending.

**Comment by nikhrao** [comment]
The error is not just in generating the crisp values but outputs don't seem appropriate for two extreme inputs meaning to say 
if input1=low 
and input2=high
then output=  exactly 0 or atmost +/- 0
where high and low have same magnitude but opposite sign conventions.

but the system is giving an erroneous output when compared to  manual calculation and other verified means.

**Comment by JDWarner** [comment]
Erroneous output would be expected when only 1/3 of the rules are actually being taken into consideration.

If you want to verify this, the system would work as expected if all rules pointing at the same Consequent Term are combined into a single, larger rule.

**Comment by nikhrao** [comment]
So  you mean to say  if the set of rules are too many the current
"skfuzzy.control" is not able to point to the desired consequent term
because all the rules are not being triggered....??

**Comment by JDWarner** [comment]
I mean to say there's a bug, and we understand what the bug is. Everything you describe and see is due to that bug, not anything else. I pointed you at an alternative way to design systems as a workaround this until the fix is up. 

All rules get triggered, but they were overwriting prior calculations if more than one pointed at the same Consequent Term. That's being fixed.

**Comment by nikhrao** [comment]
I get the point thank you. Tentatively by when can the update be
available??

**Comment by JDWarner** [comment]
@nikhrao how about now: #109  ;)

**Comment by nikhrao** [comment]
Working good !!

Thanks
