### ISSUE TITLE
Memory error applying an FIS to rasters

### ISSUE THREAD

**Issue by jtgilbert** [scikit-fuzzy/scikit-fuzzy#119]
I have 2 different classes that are used to read in raster datasets and then create an output raster dataset where each pixel is calculated using an FIS created with a control system.  The 2 input class runs fine, but the 3 input runs into a memory error.  They're not huge rasters (2600 x 4500, 45MB), and i set cache=False in the ControlSystemSimulation.  Attached is where the error comes up.
![memory_error](https://cloud.githubusercontent.com/assets/21687931/18172646/7bee650a-7023-11e6-8119-6e3a348cf71b.PNG)

**Comment by JDWarner** [comment]
Thanks for the report, @jtgilbert - It does sounds like you're using things properly. Setting cache=False _should_ avoid this problem.

Would it be possible to provide an example image and a small script, so I ensure I can easily reproduce this? I can make an image of that size, but without knowing the system details (and raster bit depth) I can't be sure to reproduce. Ideally include both systems, so I can explore the working one as well. If your work is private and/or proprietary, feel free to email me directly, though it's best if debugging can take place in a public forum.

It would also be helpful to know how much memory your system(s) have. My workstation is over 40GB, but I can spin up a VM with arbitrary lower resources for testing.

**Comment by jtgilbert** [comment]
I sent an email with my scripts and data, not sure if you got it..?

**Comment by JDWarner** [comment]
I got it. Busy here, just now playing with it. So far I'm trying to profile the runtime for the 2-input model.

Out of curiosity, what happens if you leave `cache=True`? It should purge the cache after every 1,000 runs. Do you still have memory issues?

**Comment by JDWarner** [comment]
Fix incoming, see #120. Long story short, the `Antecedent`s in the graph weren't being cleared. Seems quite stable in memory to me now.

As an aside, it's best to leave the `cache` on with a reasonable clear interval. Every time the cache is purged, a number of graph traversals have to be done - and this is costly. Doing that only every 100 or 1,000 or 10,000 times, assuming you have enough RAM, should improve performance - now without leaking ;)
