### ISSUE TITLE
Installation error in Beaglebone Black Debian 8.6

### ISSUE THREAD

**Issue by acseckin** [scikit-fuzzy/scikit-fuzzy#124]
I want to install scikit fuzzy and get this error message
````
pip install -U scikit-fuzzy
....
```
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-UKRpkC/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-NqAtte-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-UKRpkC/scipy/``

**Comment by JDWarner** [comment]
For posterity, this looks like an issue triggered by Scipy while collecting dependencies.

Not sure how it was resolved, but generally it's recommended to install Scipy from a wheel or binary, perhaps provided by the OS or Anaconda/Canopy.  The former approach is probably better for these ARM boards.

**Comment by acseckin** [comment]
I thought I solved it. It still gives an error.

**Comment by JDWarner** [comment]
Please try with pip rather than easy_install (`pip install -U scikit-fuzzy`) and then paste the full log.  These warnings are not necessarily errors that would block installation, so the real cause may not be captured above.

**Comment by acseckin** [comment]
firs error occured with `pip` and second is with `easy_install`. Now I'm trying `sudo apt-get install python-scipy`

**Comment by acseckin** [comment]
Here is the solution:

```
sudo apt-get install python-numpy
sudo apt-get install python-scipy
sudo apt-get install python-matplotlib
sudo pip install scikit-fuzzy
```

now works fine.
