### ISSUE TITLE
Problem with view() function

### ISSUE THREAD

**Issue by RubelAhmed57** [scikit-fuzzy/scikit-fuzzy#125]
I am using skfuzzy with python 2.7.x. Every time I call view() function (i.e; quality['average'].view()), just a blink like phenomenon comes. Could not find why.

**Comment by JDWarner** [comment]
Can you verify that Matplotlib works as expected on your system?  Are you running this in a script, in a Python terminal, or in something like Jupyter/IPython notebook?

Everything works as expected for me in 2.7.x in Jupyter.

**Comment by RubelAhmed57** [comment]
Tried in Jupyter, got this error:
C:\Program Files\Anaconda2\lib\site-packages\matplotlib\figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "

**Comment by RubelAhmed57** [comment]
#124 Tried in Jupyter, got this:
C:\Program Files\Anaconda2\lib\site-packages\matplotlib\figure.py:397: UserWarning: matplotlib is currently using a non-GUI backend, so cannot show the figure
  "matplotlib is currently using a non-GUI backend, "

**Comment by Chuseuiti** [comment]
I have the same problem with the rule.view(), however by adding time.sleep after the plot, it will show you the diagram.

rule.view()
time.sleep(10)

**Comment by JDWarner** [comment]
@RubelAhmed57, @Chuseuiti - when using Jupyter, are you running the line

``` python
%matplotlib inline
```

in a cell prior to `rule.view()`?  That warning is expected, but the result should be shown as the cell output.

**Comment by JDWarner** [comment]
The actual result of this call is that the Matplotlib figure is returned.  The idea is a user could further modify / customize the plot to their needs.

As a result, it doesn't make a blocking call.  If you called `plt.show()` after this, it would be shown.
