### ISSUE TITLE
Fuzzy C-means clustering of Glove vectors

### ISSUE THREAD

**Issue by Shahin-01** [scikit-fuzzy/scikit-fuzzy#127]
I have run K-means clustering of Glove semantic vectors, which works fine shown in this link with [explanation](http://douglasduhaime.com/blog/clustering-semantic-vectors-with-python) and [full source](https://gist.github.com/duhaime/9330473f9a4e288f00af) . I applied fuzzy C-means algorithm instead of K-means to compare results, however, it shows me errors. I really could not find why this code is not working. I have only changed  the full source above only in part which is Fuzzy C-means implementation. So, this is what I wrote as an FCM: `

if __name__ == "__main__":

        input_vector_file = sys.argv[1]
        n_words           = int(sys.argv[2])
        reduction_factor  = float(sys.argv[3])
        clusters_to_make  = int( n_words * reduction_factor )
        labels_array = build_word_vector_matrix(input_vector_file, n_words)
        for c, r in enumerate(input_vector_file):
            sr = r.split()
            labels_array_aslist=list(labels_array)
            cluster_labels=labels_array_aslist.append(sr[0])

        Fuzzy_C_means_model = fuzz.cluster.cmeans(input_vector_file, clusters_to_make, 2, error=0.005, maxiter=1000,init=None)
        cluster_to_words = find_word_clusters(labels_array, cluster_labels)

        for c in cluster_to_words:
           print (cluster_to_words[c])`

But it shows 

>  n = data.shape[1]
AttributeError: 'str' object has no attribute 'shape'
error. 
Could you tell me how to fix this, please ?

**Comment by Shahin-01** [comment]
@duhaime  if possible, could you take a look at this one, please ?

**Comment by duhaime** [comment]
@Shahin-01 It looks like you were trying to perform fuzzy cmeans on a file object rather than an array of numeric values. Does [this](https://gist.github.com/duhaime/5e391b72830bbc22706ae18af4393cf1) help?

**Comment by Shahin-01** [comment]
Yes, I got it, thank you very much for helping @duhaime . One more thing I would like to ask. When running that with Fuzzy-C-means,  obtained number of clusters did not correspond to the specified number. As a test,  in command line I specified    glove_50d.txt 1000 .1     which in this case clusters_to_make becomes 100, however running with fuzzy c-means several times  it produced   around 30-38 word clusters. Also, I was expecting that  at least some words might appear in two clusters as we specified m=2, however it did  not seem to appear there. What do you think the reasons are for these ?

**Comment by duhaime** [comment]
@Shahin-01 These are excellent questions; I'll try to answer them below. It's important to know that Fuzzy C means is fundamentally different from k-means. As I understand it, K-means wants to assign each input point to exactly one cluster, while fuzzy c-means wants to assign each point to all clusters in varying degrees. I have read very little on fuzzy c-means, but it seems a bit like a matrix factorization or dimension reduction technique that returns a matrix in which each input point is represented as a vector that's essentially a distribution over a given number of clusters. @JDWarner may be able to provide additional insight here.

So with this in mind, I'd try adding this after line 69:

```
print(len(u), len(u[0]), len(list(set(cluster_labels))))
```
This will show you that u is essentially a matrix, as it contains `n_words` * `reduction_factor` members, where each member has the size of an input vector. In your example above, for instance, u would contain (1000 * .1) = 100 members.

Line 69, however, examines each input vector and finds the single cluster for which that cluster has the highest weight, and it hard assigns that vector to that cluster. If you think about it, this line essentially forces fuzzy c-means to act as a k-means classifier, as it forces us to assign each point to exactly one cluster/topic. If you wanted other results--like for instance if you wanted to ensure each word was assigned not to exactly one topic but to exactly two topics--I'd play with the `u` object returned by `fuzz.cluster.cmeans()` which contains all the information you should need to do the further sub clusterings.

I hope this helps! If you have trouble with the subclustering process, you may wish to open a question on StackOverflow, as there are many more sets of eyes that can help you there than there are in this thread...

**Comment by Shahin-01** [comment]
Hmm ok, thank you very much really @duhaime , I will research about this and ask questions in StackOverflow in case I need

**Comment by JDWarner** [comment]
A similar issue was previously raised (see #94 and associated mailing list discussion).  It turns out that C-means is not well adapted to high-dimensional data, and I think this same known limitation of the algorithm is what you're running up against.  

For reference, this is definitely an appropriate place to ask questions about potential problems with Scikit-Fuzzy.  The initial question was regarding an error message, and I definitely want centralized reporting for that here.

**Comment by JDWarner** [comment]
Closing as previously answered, a known limitation of the Fuzzy C-means algorithm.
