### ISSUE TITLE
Documentation View Rule

### ISSUE THREAD

**Issue by Chuseuiti** [scikit-fuzzy/scikit-fuzzy#131]
Is there any documentation regarding the meaning of the rule diagram displayed by rule.view()?

What are all of those red dots connected..it seems like a directed graph without any meaning ..at least I dont understand the meaning of the diagram in tipping example... any documentation available?

**Comment by JDWarner** [comment]
The control module is based on NetworkX.  The graph is a direct visualization of the NetworkX graph.  Unfortunately, it is not optimized for easy visualization and the controls over the layout are limited.

I've experimented with including labels but the result gets quite complex and unusable quickly.  If anyone knows of or has ideas about a way to improve this, it would be a great PR.

**Comment by JDWarner** [comment]
See https://networkx.github.io/documentation/networkx-1.10/reference/drawing.html

I'm going to close this as answered, although this functionality could certainly be improved.
