### ISSUE TITLE
Why only 3,5,7 terms with automf? Easy modified automf...

### ISSUE THREAD

**Issue by xexeo** [scikit-fuzzy/scikit-fuzzy#140]
I needed to use more than 7 terms auto generated with automf, and it was actually simply to modify the function:
1. Delete the else that raises exception for a number other than 3,5, or 7
2. Include following code before if Invert is True
```    
if number > 7 :
        names = ['T1']
        for i in range(2,number+1):
            names.append('T'+str(i))
```

It worked like a charm for me.

**Comment by JDWarner** [comment]
There main reason is that I wanted the names to make some logical sense, and beyond 7 they ceased to have really innate meaning.  However, while I can see the draw of this convenience function for other numbers of names - I would want it to be useful when generalized.

What if there was an optional `names=` kwarg, which accepted an iterable of strings?  If this was present, and the length of it agreed with the requested number of terms, it would generate an even number and name them appropriately.

That would be a simple but useful generalization - do you agree?

**Comment by xexeo** [comment]
This seems a good solution for me. 

Maybe you could even not specify the number of terms if you use `names=`, since this would be a redundancy.

Can I make another 2 observations in this thread?

1) After I posted this, I began questioning the need for an odd number. Although the algorithm I am using (Wang & Mendel) asks for an odd numbers, and I understand the quality that a linguistic term in the center can create, many other examples in the literature simply don´t care if we have an odd or an even number of linguistic terms. 

2) I used to have a function that create the linguistic terms with a percentage of overlap. Your function always have 50% overlap between adjacent linguistic terms, but sometimes it is useful to have smaller or bigger overlaps.
