### ISSUE TITLE
Error in Rule View

### ISSUE THREAD

**Issue by sezan92** [scikit-fuzzy/scikit-fuzzy#142]
Hello , I was trying to implement the example in Python hosted website. But it is showing me following errors, although , it is showing the image

  File "/home/sezan92/anaconda2/lib/python2.7/site-packages/skfuzzy/control/rule.py", line 247, in view
    ControlSystemVisualizer(self).view().show()

AttributeError: 'tuple' object has no attribute 'show'

**Comment by JDWarner** [comment]
Thanks for the report.  I believe this is fixed in #141, just not merged in yet.  If you have the ability to try out that PR, it should fix this (and bring some significant performance improvements!).

**Comment by JDWarner** [comment]
Closed by #141.
