### ISSUE TITLE
.view()

### ISSUE THREAD

**Issue by matejko94** [scikit-fuzzy/scikit-fuzzy#145]
I am using this example: http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem_newapi.html and when I call .view(), program shows this graph and then imidiatly close it. Maybe if you have any suggestion why ?

**Comment by JDWarner** [comment]
The view method returns the matplotlib figure and axis, so further modification/tweaking may be done.

It does not show the figure (unless you're using Jupyter, which is recommended).  

To see the figure, use fig.show() or plt.show() after .view()
