### ISSUE TITLE
wrong gaussmf

### ISSUE THREAD

**Issue by ivitellisonobelli** [scikit-fuzzy/scikit-fuzzy#146]
The gaussian membership function is [defined](https://pdfs.semanticscholar.org/6b40/3432924cf325373ff806704253fa552f9981.pdf) [as](https://it.mathworks.com/help/fuzzy/gaussmf.html)

![gaussmf](https://user-images.githubusercontent.com/18249872/30519866-e3f2bc4c-9ba0-11e7-9e42-443418336ec5.png)

and yet the code that actually computes it is
` return np.exp(-((x - mean) ** 2.) / float(sigma) ** 2.)`

the denominator should be multiplied by 2.

**Comment by JDWarner** [comment]
Looks like you're right @ivitellisonobelli, thanks for the report.  This is a bug that dates all the way back to the beginning, when I converted a toolkit written for Matlab that predated their official fuzzy logic toolbox to Python.

**Comment by ivitellisonobelli** [comment]
I'm happy to help, thank you for the library.
