### ISSUE TITLE
fuzzifier functions support 

### ISSUE THREAD

**Issue by KanwalPrakashSingh** [scikit-fuzzy/scikit-fuzzy#153]
Hi 
I couldnt find any fuzzification support in cluster module, as in in the paper which talk about problems in fuzzy cmeans with high dimensional data, it is mentioned that PFCM creates an area of crisp membership values.
Am i missing something.

**Comment by scikit-fuzzy** [comment]
I'm afraid I am not sure what you are asking.

**Comment by KanwalPrakashSingh** [comment]
https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/cluster/_cmeans.py

`um = u_old ** m`
^ this part in function _cmeans0 is for fuzzification, is there a way to implement something else 

like fpcm which is like uold*(1-beta)/(1+beta)**2 + uold*2*Beta/(1+Beta)

http://fuzzy.cs.ovgu.de/aigaion/index.php/attachments/single/127

**Comment by JDWarner** [comment]
It's certainly possible to change that line as desired.  The `_cmeans.py` file is essentially self-contained; actually it doesn't depend on any part of the rest of the package - just NumPy and SciPy -  so you can prototype by extracting and playing with that file alone.

A long-standing potential project has been to improve the interface for C-means, likely with a much more intuitive class-based API similar to what Scikit-Learn exposes.  It is functional now, but far from ideal.

If you want to submit a PR with the ability to select a few different options for this, it would be welcome!

**Comment by JDWarner** [comment]
A PR would be welcome, to switch between these or implement fpcm as a separate function.  In lieu of that, closing as addressed.
