### ISSUE TITLE
Different metrics for cmeans

### ISSUE THREAD

**Issue by laurazh** [scikit-fuzzy/scikit-fuzzy#159]
I check the docs, and I don't see the option to change the metrics for the skfuzzy.cluster.cmeans(). Is it possible to change the metrics ? I guess it is by default euclidian. I was wishig to use mahalanobis.

**Comment by JDWarner** [comment]
This is certainly possible, but right now would require tweaking the actual code.  It is not currently set up to have this tweaked via keyword or similar.

I can help you walk through this, and if you'd like to see this look a particular way from an API standpoint, we can get it added as a new feature.

**Comment by laurazh** [comment]
Thanks! I actually change the _cmeans.py, and added a "metrics_" option.  I am still checking the results. Do I have to change other file ?

**Comment by JDWarner** [comment]
cmeans is fully contained in that file; that should be all you need to change.  Feel free to contribute your improvement as a PR!

**Comment by laurazh** [comment]
I push my change and set the metric by default to euclidean, I run the code on my side and it seems to work. I try to run with sparse data using mahalanobis, but i get a LinalgError, singular matrix. I think it is directly linked to how mahalanobis is compute.
