### ISSUE TITLE
a bug in controlsystem.py

### ISSUE THREAD

**Issue by mmkamani7** [scikit-fuzzy/scikit-fuzzy#161]
I came across this bug in the file controlsystem.py that might affect others as well.
In the line 181:
```python
value = np.fmax(value, np.var.universe.min())
```
whereas the `np.var` has no attribute `universe`. It gave me error under some circumstances. 

Manual Solution:
I just remove the `np` from `np.var.universe.min()` and use it without error.

**Comment by JDWarner** [comment]
Hmm, indeed that's obviously wrong yet managed to slip through.  Thanks for the report!

Will fix and ensure the fix is tested.  I'm surprised that didn't break things sooner.
