### ISSUE TITLE
Name mismatched? The Tipping Problem - The Hard Way

### ISSUE THREAD

**Issue by SandGreif** [scikit-fuzzy/scikit-fuzzy#183]
Hello guys,</br>

i read the  The Tipping Problem - The Hard Way example on the Website (
https://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem.html).
It's about the Topic aggregation see below.
I read in a book that the correct technical term would be accumulation instead aggregation?
</br></br>

_"Rule Aggregation </br>
 With the activity of each output membership function known, all output membership functions must be combined. This is typically done using a maximum operator. This step is also known as Aggregation."_

**Comment by JDWarner** [comment]
There are a few areas in fuzzy logic literature/texts where certain terms are not consistently applied.  I believe what really matters is consistency, and I do believe within the package and documentation we have been consistent.

However, if there is consensus in the literature please point me at a few references and I'd be happy to revise the term.  Fortunately this requires no API changes, it's strictly in the documentation and comments.

Closing for now, but as stated feel free to convince me!
