### ISSUE TITLE
Error in `generatemf.py` AttributeError: 'list' object has no attribute 'max'

### ISSUE THREAD

**Issue by behdadahmadi** [scikit-fuzzy/scikit-fuzzy#184]
My code :
```
df['Lupper'] = ((df.High - np.maximum(df.Open, df.Close))/df.Open) * 10
df['Llower'] = ((np.minimum(df.Open, df.Close) - df.Low)/df.Open) * 10
df['Lbody'] = ((np.maximum(df.Open, df.Close) - np.minimum(df.Open, df.Close))/df.Open) * 10
N = piecemf([df.Lupper,df.Lbody,df.Llower],abc=[0.35, 0.5, 1])
```
It returns error:
```
Traceback (most recent call last):
  File "/Users/behdad/PycharmProjects/Fuzzy/DataframeSetup.py", line 13, in <module>
    N = piecemf([df.Lupper,df.Lbody,df.Llower],abc=[0.35, 0.5, 1])
  File "/Users/behdad/PycharmProjects/Fuzzy/lib/python2.7/site-packages/skfuzzy/membership/generatemf.py", line 177, in piecemf
    if c != x.max():
AttributeError: 'list' object has no attribute 'max'
```

What's the problem? Am I using the function correct?

**Comment by JDWarner** [comment]
Ah, this particular function assumes the input universe is a numpy array which would have a max method.  Your input universe is a list.

The function should probably sanitize universe so this error doesn't happen, but for now you can just create a two element numpy array and everything should work.

**Comment by behdadahmadi** [comment]
@JDWarner  Thank you. I did it and solved. But what is wrong with input `abc`?
`N = piecemf(np.array([df.Lupper,df.Lbody,df.Llower]),abc=[0.35, 0.5, 1])`

Error:
```
Traceback (most recent call last):
  File "/Users/behdad/PycharmProjects/Fuzzy/DataframeSetup.py", line 13, in <module>
    N = piecemf(np.array([df.Lupper,df.Lbody,df.Llower]),abc=np.array([0.35, 0.5, 1]))
  File "/Users/behdad/PycharmProjects/Fuzzy/lib/python2.7/site-packages/skfuzzy/membership/generatemf.py", line 180, in piecemf
    assert a <= b and b <= c, '`abc` requires a <= b <= c.'
AssertionError: `abc` requires a <= b <= c.
```

**Comment by JDWarner** [comment]
@behdadahmadi I've gone over this forward and backward.

The only way this could happen is if your universe max value was so low as to make *both* `b` and `c` above the universe max.  Only `c` is checked at runtime, so it could in this specfiic case be corrected and then the required relationship between `a`, `b`, and `c` would be broken.
