### ISSUE TITLE
defuzzification methods mom/lom uses absolute values

### ISSUE THREAD

**Issue by jfpower** [scikit-fuzzy/scikit-fuzzy#188]
Hi,

I was looking at the code for the som/lom defuzzification methods, where the crisp value is calculated as the smallest/largest x-value that gives the maximum membership.  I was having a problem in the case where some of the x-values can be negative.  The lom/som defuzzification  is implemented in defuzzify.py to only work with the absolute value of the x variables, so you always get an x-value above 0.  I had expected -2 rather than 1 from the following:

  In: defuzz(np.array([-2,-1,0,1,2]), np.array([1,0,0,1,0]), 'som')
  Out: 1

I thought at first that it wasn't intended for it to work with negative x-values, but then there's no need for the abs function.  The simple solution is not to use abs here, so I was wondering if it is in there for a reason?

In any case this causes a problem (index out of bounds) when all the maxima are in the negative range for x, since then no indices are collected.  For example:

  In: defuzz(np.array([-2,-1,0,1,2]), np.array([1,1,0,0,0]), 'som')
  ...
  IndexError: index 0 is out of bounds for axis 0 with size 0

Source reference:
https://github.com/scikit-fuzzy/scikit-fuzzy/blob/cde5a2a2e89c77f1de900b03193cedca8689957b/skfuzzy/defuzzify/defuzz.py#L261

**Comment by JDWarner** [comment]
Thanks for the detailed report, @jfpower - this certainly does appear to be a bug.  

Referring back to the original Matlab source by Dr. Hal Ottesen, this `abs` was present going back to 1992.  However, I cannot think of *any* reason there would be a limitation here for exclusively positive or negative universe values.

This is a significant enough issue that I'd like to push another release after it's fixed.

Would you like to make a PR fixing it?  If not I'm happy to do so, but deserve the credit if you'd like.

**Comment by jfpower** [comment]
Hi, thanks for the quick reply.  I thought I'd make a PR fixing this, as it was a very simple edit.  However the branch I pushed is failing the CI tests, on an apparently unrelated file (that I didn't edit).  Could you point me in the right direction so I can fix this?

**Comment by JDWarner** [comment]
Closed by #189
