### ISSUE TITLE
A question on the 'm' parameter

### ISSUE THREAD

**Issue by parishcm** [scikit-fuzzy/scikit-fuzzy#191]
Just a question. 

If we look at MATLAB or Wikipedia, we see that the fuzzy c-means 'm' is restricted to m>1. In skfuzzy, the cmeans method will accept m<1, although m==1 gives divide by zero and m nearly 1 gives numerical instability. In MATLAB fcm I could use m=1.05, say, to converge towards the K-means result. I feel like I am suffering a fundamental misunderstanding in how m in skfuzzy relates to m in MATLAB or other implementations. I just ran a batch of 16 runs with m=0.8, chose the ones with best fpc and best objective function, and got (very funny looking) results. Can you point me in the right direction, please?

Sorry if this is the wrong venue for this question.

https://www.mathworks.com/help/fuzzy/fcm.html
https://en.wikipedia.org/wiki/Fuzzy_clustering#General_description
(etc.)

```
(base) C:\Users\redacted>conda list scikit-fuzzy
# packages in environment at C:\work\Anaconda3:
#
# Name                    Version                   Build  Channel
scikit-fuzzy              0.3.1                     <pip>
```

**Comment by JDWarner** [comment]
Quite simply we just don't restrict the value of `m`.  All of your points are valid as far as I know; I'm not certain why one would want `m < 0`.  However, I tend to error on the side of not assuming or setting barriers for the user.

In this case it seems `m` really shouldn't be less than zero, as it likely results in difficulty with convergence.
