### ISSUE TITLE
New minor release?

### ISSUE THREAD

**Issue by schadocalex** [scikit-fuzzy/scikit-fuzzy#193]
Hi,

I would want to know if any minor release is planned. There are bugs like https://github.com/scikit-fuzzy/scikit-fuzzy/commit/d9bac7a53d8e64f69f71b0fb4da2c8921b6aa7d0 that forced me to manually install the library. All of my coworkers will have to do the same if there is no release.

**Comment by JDWarner** [comment]
Yes, as soon as the unit tests are sorted out - it's likely time for a major release, actually.  A few significant improvements have been added.

**Comment by schadocalex** [comment]
https://github.com/scikit-fuzzy/scikit-fuzzy/releases/tag/0.4.0 is released!

Thanks!
