### ISSUE TITLE
How can I add multiple outputs to the consequent in a rule?

### ISSUE THREAD

**Issue by marcojulioarg** [scikit-fuzzy/scikit-fuzzy#195]
Hello, I'm trying to add multiple mf activations in a rule containing multiple consequents and I dont know if this can be done.

Thank you

**Comment by EnyuCao** [comment]
Hi,
I checked [the Rule API document](https://pythonhosted.org/scikit-fuzzy/api/skfuzzy.control.html?highlight=controlsystemsimulation#skfuzzy.control.Rule), and it says

> Consequent terms serving as outputs from this rule. Multiple terms may be combined using operators | (OR), & (AND), ~ (NOT), and parentheticals to group terms.

Also I check the rule file and get this useful information: 
```
        Accept consequents in four formats:
         a) Unweighted single output.
            e.g.: output['term']
         b) Weighted single output
            e.g.: (output['term']%0.5)
         c) Unweighted multiple output
            e.g.: (output1['term1'], output2['term2'])
         d) Weighted multiple output
            e.g.: ( (output1['term1']%1.0), (output2['term2']%0.5) )
```

**Comment by JDWarner** [comment]
@enyucao is correct, go with the rule source file.  There is no meaning to combining consequents with those operators.

The consequent documentation will be patched.
