### ISSUE TITLE
Question: Why am I getting 8.3333 at the top of my antecedent range? 

### ISSUE THREAD

**Issue by lppier** [scikit-fuzzy/scikit-fuzzy#196]
import numpy as np
import skfuzzy.control as ctrl
import skfuzzy as fuzz

income = ctrl.Antecedent(np.arange(0, 11, 1), 'income')
investment_score = ctrl.Consequent(np.arange(0, 11, 1), 'investment_score')
income.automf(3)
investment_score.automf(3)
income.view()
investment_score.view()

rule1 = ctrl.Rule(income['poor'], investment_score['poor'])
rule2 = ctrl.Rule(income['average'], investment_score['average'])
rule3 = ctrl.Rule(income['good'], investment_score['good'])
investment_score_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])
investment_score_t = ctrl.ControlSystemSimulation(investment_score_ctrl)
investment_score_t.input['income'] = 10

investment_score_t.compute()
print (investment_score_t.output['investment_score'])
investment_score.view(sim=investment_score_t)

I get investment score equals 8.3333333. I was expecting 10 because I entered income = 10 (the very maximum). 
Is 8,.3333 correct, and my understand of fuzzy has some errors? 

Thank you.

**Comment by JDWarner** [comment]
Yes, this is correct behavior.  The result is the centroid of the final, activated membership function.  That function, as defined here, is a triangle from 5 (membership 0) to 10 (membership 1).  When you find the centroid of this, it's 8.333.

**Comment by lppier** [comment]
Thank you for the clarification @JDWarner !
