### ISSUE TITLE
How to get the mf value after defining a gaussian bell mf using skfuzzy?

### ISSUE THREAD

**Issue by steve7an** [scikit-fuzzy/scikit-fuzzy#199]
Sorry for the super noob question here, but i'm trying to use the skfuzzy framework to create some gaussian bell membership function, as follows

    import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# New Antecedent/Consequent objects hold universe variables and membership
# functions
quality = ctrl.Antecedent(np.arange(0, 11, 1), 'quality')
service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
tip = ctrl.Consequent(np.arange(-30, 30, 1), 'tip')

# Auto-membership function population is possible with .automf(3, 5, or 7)
quality.automf(3)
service.automf(3)

# Custom membership functions can be built interactively with a familiar,
# Pythonic API
#tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
#tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
#tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])
arr = []
sigma = 2.5
tip["EL"] = fuzz.gaussmf(tip.universe, -30, sigma)
tip["VL"] = fuzz.gaussmf(tip.universe, -20, sigma)
tip["L"] = fuzz.gaussmf(tip.universe, -10, sigma)
tip["M"] = fuzz.gaussmf(tip.universe, 0, sigma)
tip["H"] = fuzz.gaussmf(tip.universe, 10, sigma)
tip["VH"] = fuzz.gaussmf(tip.universe, 20, sigma)
tip["EH"] = fuzz.gaussmf(tip.universe, 30, sigma)

tip.view()
and after creating this, I would like to be able to get the value back based on each fuzzy segment that I've created as follows, tip["EH"].input = 5 and based on the bell curve created, I would like to get back the membership function value as per the plot. I've looked through the document but was'nt able to get it. Please help! Thanks

**Comment by EnyuCao** [comment]
Hi Steve,
The Github is using Markdown. So I clean it a bit.
```
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# New Antecedent/Consequent objects hold universe variables and membership functions
quality = ctrl.Antecedent(np.arange(0, 11, 1), 'quality')
service = ctrl.Antecedent(np.arange(0, 11, 1), 'service')
tip = ctrl.Consequent(np.arange(-30, 30, 1), 'tip')

# Auto-membership function population is possible with .automf(3, 5, or 7)
quality.automf(3)
service.automf(3)

#Custom membership functions can be built interactively with a familiar, Pythonic API

#tip['low'] = fuzz.trimf(tip.universe, [0, 0, 13])
#tip['medium'] = fuzz.trimf(tip.universe, [0, 13, 25])
#tip['high'] = fuzz.trimf(tip.universe, [13, 25, 25])
arr = []
sigma = 2.5
tip["EL"] = fuzz.gaussmf(tip.universe, -30, sigma)
tip["VL"] = fuzz.gaussmf(tip.universe, -20, sigma)
tip["L"] = fuzz.gaussmf(tip.universe, -10, sigma)
tip["M"] = fuzz.gaussmf(tip.universe, 0, sigma)
tip["H"] = fuzz.gaussmf(tip.universe, 10, sigma)
tip["VH"] = fuzz.gaussmf(tip.universe, 20, sigma)
tip["EH"] = fuzz.gaussmf(tip.universe, 30, sigma)

tip.view()
'''
and after creating this, I would like to be able to get the value back based on each fuzzy segment that I've created as follows, tip["EH"].input = 5 and based on the bell curve created, I would like to get back the membership function value as per the plot. I've looked through the document but was'nt able to get it. Please help! Thanks
'''
```

If I didn't misunderstand, you want to visualize the the membership value when Tip is 5. Please take a look at the code below.

```
#!/usr/bin/env python
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# New Antecedent/Consequent objects hold universe variables and membership functions

tip = ctrl.Antecedent(np.arange(-30, 30, 0.1), 'tip')
null= ctrl.Consequent(np.arange(0, 30, 1), 'null')

# Auto-membership function population is possible with .automf(3, 5, or 7)
null.automf(3)

#Custom membership functions can be built interactively with a familiar, Pythonic API
arr = []
sigma = 2.5
tip["EL"] = fuzz.gaussmf(tip.universe, -30, sigma)
tip["VL"] = fuzz.gaussmf(tip.universe, -20, sigma)
tip["L"] = fuzz.gaussmf(tip.universe, -10, sigma)
tip["M"] = fuzz.gaussmf(tip.universe, 0, sigma)
tip["H"] = fuzz.gaussmf(tip.universe, 10, sigma)
tip["VH"] = fuzz.gaussmf(tip.universe, 20, sigma)
tip["EH"] = fuzz.gaussmf(tip.universe, 30, sigma)

#tip.view()
'''
and after creating this, I would like to be able to get the value back based on each fuzzy segment that I've created as follows, tip["EH"].input = 5 and based on the bell curve created, I would like to get back the membership function value as per the plot. I've looked through the document but was'nt able to get it. Please help! Thanks
'''

rule =   ctrl.Rule(tip["EH"],null['good'])


ctrl_sys = ctrl.ControlSystem([rule])

ctrl_instance = ctrl.ControlSystemSimulation(ctrl_sys)

ctrl_instance.input['tip'] = 5

ctrl_instance.compute()

tip.view(sim=ctrl_instance)

raw_input()
```
The output of the script is the figure below
![issue199](https://user-images.githubusercontent.com/32489681/46084210-6b5eb900-c1a3-11e8-88df-77b8ae522547.png)

**Comment by steve7an** [comment]
Hi @EnyuCao 
Thanks for your prompt response and help! 👍 
So basically I would need to create a rule, even a null one to be able to get the MF value back right?
I'm interested to get the MF value based on the plot and not just the visualisation itself, so for example using the same example of input["tip"] = 5, am I able to get back which fuzzy area it is in, i.e. M and H back and also the membership value (the y axis), maybe 0.1?

**Comment by EnyuCao** [comment]
For the first question, I think the answer is yes. And not only the rule, but also the `ctrl.ControlSystem` and `ctrl.ControlSystemSimulation`. The reason  is that the FLS system is dynamic before a simulation (see this [issue reply](https://github.com/scikit-fuzzy/scikit-fuzzy/issues/194#issuecomment-419162129)). Only with a simulation, a input is valid.

About the value, maybe this function `print_state` is useful. If you add this line to the script,
`print ctrl_instance.print_state()`
the output will be
```
=============
 Antecedents 
=============
Antecedent: tip                     = 5
  - EL                              : 2.74878500791e-43
  - VL                              : 1.92874984796e-22
  - L                               : 1.52299797447e-08
  - M                               : 0.135335283237
  - H                               : 0.135335283237
  - VH                              : 1.52299797447e-08
  - EH                              : 1.92874984796e-22

=======
 Rules 
=======
RULE #0:
  IF tip[EH] THEN null[good]
	AND aggregation function : fmin
	OR aggregation function  : fmax

  Aggregation (IF-clause):
  - tip[EH]                                                : 1.92874984796e-22
                                                   tip[EH] = 1.92874984796e-22
  Activation (THEN-clause):
                                                null[good] : 1.92874984796e-22


==============================
 Intermediaries and Conquests 
==============================
Consequent: null                     = 0.000273908532446
  poor:
    Accumulate using accumulation_max : None
  average:
    Accumulate using accumulation_max : None
  good:
    Accumulate using accumulation_max : 1.92874984796e-22


```

**Comment by steve7an** [comment]
Ok that seems like need to dig in a bit deep into the code to modify it, but I'm quite surprised that we're able to plot it so easily but we're not able to easily retrieve the membership function value? Let's say if i don't need to know which fuzzy zones it's in now but just need the mf value, is there an easy function to call to get it? Thanks so much!!

**Comment by EnyuCao** [comment]
I totally agree that this package make programming much easier. I am not able to answer your question whether that easy function exists, so leave it to the main developer. :) 

Actually, the comments in the source code are very interesting.  

Besides, I think this source[ code segment](https://github.com/scikit-fuzzy/scikit-fuzzy/blob/master/skfuzzy/control/controlsystem.py#L507) is useful for you.

**Comment by steve7an** [comment]
Thanks, guess will refer to the print state function to retrieve what I need for now. 👍

**Comment by jfpower** [comment]
Hi, I wonder if I've understood correctly: do you just want the mf value?  There's a field called `mf` in a Term object that holds an array of these values, so you can get at it directly as `tip['M'].mf`.

To map a value from the input domain you need to find where it is in the variable's `universe`, and then use this position to access the mf array, or interpolate if your value falls in between the positions.  NumPy can do this interpolation for you; for example:

```
inval = 5
for t in tip.terms: 
  mval = np.interp(inval, tip.universe, tip[t].mf)
  print(t, mval)
```

**Comment by JDWarner** [comment]
@jfpower is correct and this is the proper way to access the membership values for a particular Term.

However @steve7an, if you really just want the membership function itself rather than do anything else with it, you can use the functions `skfuzzy.gaussmf` to make the function and `skfuzzy.interp_membership` to obtain the membership values which would be used in calculation for any arbitrary point in the universe, not just the specific points defined.  Please note linear interpolation is used in the latter case.
