### ISSUE TITLE
Clustering according to one column is impossible in scikit-fuzzy

### ISSUE THREAD

**Issue by mahtabs** [scikit-fuzzy/scikit-fuzzy#200]
Hi
As the documentation said the input of the scikit-fuzzy should be a 2d array but I need to cluster my data according to one attribute. My data-set is made of 5 attributes which are [ costumNumber ,Term_to_Month ,kwconsumption ,Term_to_Day ,term_to_year ].
I am trying to cluster my data according to 'kwconsumption' attribute but after clustering all records were copied into all clusters. I think there are some problems with one dimensional data. Please give me some information to solve this problem.

**Comment by JDWarner** [comment]
I believe you can still use `cmeans` for this, though its true power is with more than one clustering attribute.  Simply ensure your array is two dimensional - so for 200 samples, you would reshapre your presumed 1D array into a 2D array of size (1, 200).

If you have any trouble with this, feel free to reopen.
