### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by menusha95** [scikit-fuzzy/scikit-fuzzy#212]
hi, I'm getting this error while executing the tipping sample after line
tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/skfuzzy/control/controlsystem.py in _process_rules(self, rules)
    774             # All done!
--> 775             raise StopIteration()
    776         else:

StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-5-eade294605ed> in <module>
----> 1 tipping_ctrl = ctrl.ControlSystem([rule1, rule2, rule3])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/skfuzzy/control/controlsystem.py in __init__(self, rules)
     45             if hasattr(rules, '__iter__'):
     46                 for rule in rules:
---> 47                     self.addrule(rule)
     48             else:
     49                 try:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/skfuzzy/control/controlsystem.py in addrule(self, rule)
     98         # Ensure no label duplication
     99         labels = []
--> 100         for r in self.rules:
    101             if r.label in labels:
    102                 raise ValueError("Input rule cannot have same label, '{0}', "

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/skfuzzy/control/controlsystem.py in __iter__(self)
    728             #  than we created the rule order for.  Thus, make new cache
    729             self._init_state()
--> 730             self._cache = list(self._process_rules(self.all_rules[:]))
    731             self._cached_graph = self.control_system.graph
    732 

**RuntimeError: generator raised StopIteration**

**Comment by rafaelfiviola** [comment]
I see you closed this, did you manage to solve it? It's happening here too! 

Python 3.7.3 and exact the same trace!

**Comment by JDWarner** [comment]
@rafaelfiviola Yes it's been fixed in master.  0.4.1 was just pushed to PyPi.
