### ISSUE TITLE
Error in Defuzzification

### ISSUE THREAD

**Issue by KMuthusamyms** [scikit-fuzzy/scikit-fuzzy#217]
Code:
emotions=ctrl.Antecedent(np.arange(0,100,1),'emotions')
exam=ctrl.Antecedent(np.arange(0,100,1),'exam')
Feedback=ctrl.Antecedent(np.arange(0,100,1),'Feedback')
course=ctrl.Consequent(np.arange(0,100,1),'course') 

Error:

 File "C:\ProgramData\Anaconda2\lib\site-packages\skfuzzy\control\controlsystem.py", line 373, in compute
    CrispValueCalculator(consequent, self).defuzz()

  File "C:\ProgramData\Anaconda2\lib\site-packages\skfuzzy\control\controlsystem.py", line 589, in defuzz
    raise ValueError("Crisp output cannot be calculated, likely "

ValueError: Crisp output cannot be calculated, likely because the system is too sparse. Check to make sure this set of input values will activate at least one connected Term in each Antecedent via the current set of Rules.

**Comment by JDWarner** [comment]
This is working as intended, telling you your system and rules are not sufficient to describe the entire system's input space.  It happens when some input would result in a completely zero combined membership; the defuzzed value cannot be defined.
