### ISSUE TITLE
Installing the scikit-fuzzy on Raspberry

### ISSUE THREAD

**Issue by lmartins30** [scikit-fuzzy/scikit-fuzzy#223]
I'm trying to install the scikit-fuzzy on my raspberry (running ubuntu) but a certificate error happens. A photo will be attached to show the error.

I downloaded the files from the git with the 'git clone' command but when I do the 'pip install -e .' command. It appears the following:
![67403311_1124539487742280_7203715325777412096_n](https://user-images.githubusercontent.com/52186112/62167899-969dc180-b2fa-11e9-994b-843069b51d35.jpg)

**Comment by JDWarner** [comment]
This is an issue with obtaining the prerequisite SciPy, not scikit-fuzzy.  I'm pretty sure SciPy can be used on the Raspberry Pi; check with them about how to resolve this.

**Comment by lmartins30** [comment]
I have SciPy version 0.17.0 installed on the Raspberry.

**Comment by JDWarner** [comment]
Ensure that your SciPy is not in a different virtual environment and can be seen by Pip, or consider upgrading it to be sure.  Pip is not finding an existing install above 0.9.0, then going out and trying to get one (it's trying to grab 1.3.0), or it would say requirement already satisfied as it does for NumPy.

**Comment by KhaiCyber** [comment]
I know my commenr which is very stupid. I had to try install scikit-fuzzy on my raspberry, but it was failed and didn't work. I don't the reason. If someone know you can comment and help me solve the problem because i really need scikitf-fuzzy for my project.
Thanks guys
