### ISSUE TITLE
Error while try tip problem  -  tipping.print_state()

### ISSUE THREAD

**Issue by luizgrj** [scikit-fuzzy/scikit-fuzzy#225]
Hi! 
When I test the tip problem control with new API I receive this message below when I use 

tipping.print_state()

Could anyone help me please?

=============
 Antecedents 
=============
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-c902f8c82681> in <module>
      8 tipping.compute()
      9 
---> 10 tipping.print_state()

~\Anaconda3\lib\site-packages\skfuzzy\control\controlsystem.py in print_state(self)
    502         print("=============")
    503         for v in self.ctrl.antecedents:
--> 504             print("{0:<35} = {1}".format(v, v.input[self]))
    505             for term in v.terms.values():
    506                 print("  - {0:<32}: {1}".format(term.label,

**TypeError: unsupported format string passed to Antecedent.__format__**

**Comment by XxHalbfettxX** [comment]
I had the same Problem.
Switching back to Python 2.7 worked for me.

**Comment by Aite** [comment]
I have the same problem,
Switching back to Python 2.7 seems more like a workaround than a fix
this shouldn't be a reason to close the issue

**Comment by maualima** [comment]
I have the same problem! I am looking for a fix

**Comment by Aite** [comment]
I've used the develop version of the library (installed from source) to make it work:
`python setup.py develop`

**Comment by ceefour** [comment]
Please release a version compatible with Python 3.x with this fix
