### ISSUE TITLE
Networkx 2.4 does not have add_path attribute anymore

### ISSUE THREAD

**Issue by AsadNoman** [scikit-fuzzy/scikit-fuzzy#229]
I keep getting this error. I had to downgrade to 2.3 to make my script work. Please fix this problem. I am using scikit-fuzzy for my Soft Computing course and have encouraged my friends to use this as well. 
Thanks

**Comment by americoalmeida** [comment]
Im having the same issue.

**Comment by americoalmeida** [comment]
Im experiencing the same issue.

**Comment by JDWarner** [comment]
Closed by #230.  

I'll cut a new minor point release this weekend.
