### ISSUE TITLE
Breaks in Anaconda Python 3.7

### ISSUE THREAD

**Issue by dougransom** [scikit-fuzzy/scikit-fuzzy#233]
I tried using the library in Anaconda with Python 3.7, attempting to use  both pip and conda to install.  I tried using an older networkx but that resulted in matplotlib problems.

`rule1 = ctrl.Rule(quality['poor'] | service['poor'], tip['low'])
rule2 = ctrl.Rule(service['average'], tip['medium'])
rule3 = ctrl.Rule(service['good'] | quality['good'], tip['high'])
rule1.view()
`
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-645910e12730> in <module>
----> 1 rule1.view()

~\Anaconda3\envs\nsb37\lib\site-packages\skfuzzy\control\rule.py in view(self)
    307         Show a visual representation of this Rule.
    308         """
--> 309         return ControlSystemVisualizer(self).view()
    310 
    311     def view_n(self):

~\Anaconda3\envs\nsb37\lib\site-packages\skfuzzy\control\visualization.py in view(self)
    192         inline.
    193         """
--> 194         nx.draw(self.ctrl.graph, ax=self.ax)
    195         return self.fig, self.ax
    196 

~\Anaconda3\envs\nsb37\lib\site-packages\skfuzzy\control\rule.py in graph(self)
    293         for t in self.antecedent_terms:
    294             assert isinstance(t, Term)
--> 295             graph.add_path([t, self])
    296             graph = nx.compose(graph, t.parent.graph)
    297 

AttributeError: 'DiGraph' object has no attribute 'add_path'`

**Comment by dougransom** [comment]
I guess the solution might be to upgrade the version of networkx skfuzzy uses.

**Comment by dougransom** [comment]
I see there have been unreleased changes that fix this.  I downloaded the lates code today and installed it in my python environment and the problem above as been addressed.  

I look forward to  a release.

**Comment by viniciusarruda** [comment]
I am having the same issue. I installed with `pip install scikit-fuzzy`, python 3.6.7 and Ubuntu 18.04.

**Comment by JDWarner** [comment]
The forward and backward compatible fixes are now live on PyPi and will be on conda-forge shortly.
