### ISSUE TITLE
DeprecationWarning for 'imp' package

### ISSUE THREAD

**Issue by simonrp84** [scikit-fuzzy/scikit-fuzzy#234]
Hello,
I'm running the 0.4.2 version of `skfuzzy` and have recently started seeing the following warning:
```DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```
This happens on the latest python `3.7` version. Thought I'd give you a heads-up as presumably this import will break at some point in the future.

**Comment by wouter-vdb** [comment]
Fixed in #5b4d3a1.

**Comment by tianyizheng02** [comment]
@JDWarner Could we close this issue since it's been fixed?

**Comment by simonrp84** [comment]
Sorry, I'll close that now.
