### ISSUE TITLE
Importing skfuzzy.control fails due to matplotlib absence

### ISSUE THREAD

**Issue by MarcoMiretti** [scikit-fuzzy/scikit-fuzzy#246]
While `matplotlib` is _not_ a dependency for `skfuzzy` (although it is for the docs). Is necessary when importing `skfuzzy.control`.

This could be easily solved replacing `import matplotlib.pyploy as plt` with:

```python
try:
    import matplotlib.pyplot as plt
except ImportError:
    pass
```

If it's ok, i could do this changes :+1:

**Comment by JDWarner** [comment]
Good catch, go ahead by all means.  Especially on limited hardware Matplotlib should not be required.
