### ISSUE TITLE
Wrong size for u in the doc?

### ISSUE THREAD

**Issue by dcabanas** [scikit-fuzzy/scikit-fuzzy#248]
Hi,

In the _cmeans_ constructor it says that the matrix _u_ returned has dimension (S, N), where _S_ is the number of features and _N_ is the number of observations. I'm running cmeans for 3...7 clusters, and I'm simply giving the model my data, respecting the doc (S, N) but _u_ has always (3, N), (4, N) etc. Is it me doing something wrong or is the documentation that has a typo and should say (c, N) where c is the number of requested clusters?

**Comment by erikmaruskin** [comment]
I was confused too. There is a typo in the documentation it should be (c,N).

**Comment by glicerico** [comment]
same here, agree with your observation, but I don't know how to submit a fix

**Comment by jannisborn** [comment]
Have a look at this PR: https://github.com/scikit-fuzzy/scikit-fuzzy/pull/271

This PR fixes it, so the tip of `master` is correct, but the deployed docs are unfortunately still incorrect: https://pythonhosted.org/scikit-fuzzy/api/skfuzzy.cluster.html?highlight=cmeans#skfuzzy.cluster.cmeans

it would be great if a new version could be released :)

**Comment by JDWarner** [comment]
Thanks @jannisborn - this is indeed fixed and was closed by #271. Sadly the pythonhosted doc platform is archived and can no longer be changed; the current auto-built documentation is available at https://scikit-fuzzy.github.io/scikit-fuzzy/overview.html
