### ISSUE TITLE
Tipping Example Incremented by 1

### ISSUE THREAD

**Issue by wwjd1234** [scikit-fuzzy/scikit-fuzzy#253]
In the tipping problem example:

quality = ctrl.Antecedent(np.arange(0, 11, 1), 'quality')

The quality is on a score of 0-10

Why is the Antecedent 0-11?

Also what is the input array meaning 0,11,1 ?

**Comment by JDWarner** [comment]
The example is correct.  Numpy's `arange` works the same as Python's `range`; the stop value is exclusive.  Please see https://numpy.org/doc/stable/reference/generated/numpy.arange.html for additional details.
