### ISSUE TITLE
Warning when trying to view

### ISSUE THREAD

**Issue by wwjd1234** [scikit-fuzzy/scikit-fuzzy#254]
When calling view()

I get the following: 

UserWarning: Matplotlib is currently using module://ipykernel.pylab.backend_inline, which is a non-GUI backend, so cannot show the figure.
  fig.show()

**Comment by wwjd1234** [comment]
import matplotlib
matplotlib.use( 'tkagg' ) 

Adding that helped

**Comment by JDWarner** [comment]
This is a warning only, related to Matplotlib and how it is configured with your particular Python setup.
