### ISSUE TITLE
Latest Version Documentation

### ISSUE THREAD

**Issue by Sinansi** [scikit-fuzzy/scikit-fuzzy#258]
Hello,

Where is the documentation of the latest version 0.4.2?

The most recent documentation I found is for 0.3 development.

Additionally, the website seems outdated as well.
The site homepage is still from version 0.2.

Could someone confirm if this library is still active or got deprecated?

Thank you!

**Comment by JDWarner** [comment]
No deprecation, active.

PyPi stopped hosting documentation and froze all existing content suddenly.  Both sites mentioned were actually hosted on PyPi.  This project is a labor of love and does not have an independent domain.

Incremental release notes are available in the project Release descriptions.  The full documentation can be built by cloning the repository, entering the `docs` top-level subdirectory, and running `make` - the docs require Sphinx and scikit-image.

If you or anyone is interested in revamping the docs infrastructure and migrating to say readthedocs, it would be greatly appreciated.  I can provide technical support, but my bandwidth is limited and I am not able to dedicate time for new features or nice-to-haves.

**Comment by JDWarner** [comment]
Going to label this as enhancement and keep it open in case someone would be interested in assisting in migrating the docs to readthedocs and adding CI build triggers.  Please feel free to reach out if you are interested.

**Comment by kinow** [comment]
The project I am working on has just finished some GitHuh actions integration.

I might be able to prepare a PR with example soluyion on my fork.

Any preference for hosting? GitHub pages? ReadTheDocs?

**Comment by JDWarner** [comment]
GitHub pages might actually be simpler/easier as I think ReadTheDocs wants to do its own build from scratch.  It's been a couple years, but certain parts of the Sphinx/NumPyDoc infrastructure didn't work quite right in RTD when last I attempted to integrate with that service.  Our docs also hook into scikit-image to generate the project logo, so it might be simpler to just deploy the generated HTML into GitHub pages.

That said, if you have experience with RTD I have nothing against will not argue with any functional improvement!
