### ISSUE TITLE
Can someone help me see what is wrong in my code?

### ISSUE THREAD

**Issue by xysh0826** [scikit-fuzzy/scikit-fuzzy#259]
I am a newcomer. I wrote a small program but there are bugs. However, I can't find what is wrong. Can someone help me?

import skfuzzy as fuzz
import numpy as np
import skfuzzy.control as ctrl

# Set the range of variables
x_Bodenfeuchtigkeit_range = np.arange(0, 1, 0.001)
x_Bodentemperatur_range = np.arange(0, 1, 0.001)
y_Bewaesserungszeit_range = np.arange(0, 1, 0.001)

# Create fuzzy control variables
x_Bodenfeuchtigkeit = ctrl.Antecedent(x_Bodenfeuchtigkeit_range, 'Bodenfeuchtigkeit')
x_Bodentemperatur = ctrl.Antecedent(x_Bodentemperatur_range, 'Bodentemperatur')
y_Bewaesserungszeit = ctrl.Antecedent(y_Bewaesserungszeit_range, 'Bewaesserungszeit')

# Define fuzzy sets and membership functions
x_Bodenfeuchtigkeit['Nichts'] = fuzz.gaussmf(x_Bodenfeuchtigkeit_range, 0, 0.08)
x_Bodenfeuchtigkeit['NB'] = fuzz.gaussmf(x_Bodenfeuchtigkeit_range, 0.25, 0.08)
x_Bodenfeuchtigkeit['MB'] = fuzz.gaussmf(x_Bodenfeuchtigkeit_range, 0.5, 0.08)
x_Bodenfeuchtigkeit['HB'] = fuzz.gaussmf(x_Bodenfeuchtigkeit_range, 0.75, 0.08)
x_Bodenfeuchtigkeit['SHB'] = fuzz.gaussmf(x_Bodenfeuchtigkeit_range, 1, 0.08)
x_Bodentemperatur['Nichts'] = fuzz.gaussmf(x_Bodentemperatur_range, 0, 0.08)
x_Bodentemperatur['NTB'] = fuzz.gaussmf(x_Bodentemperatur_range, 0.25, 0.08)
x_Bodentemperatur['MTB'] = fuzz.gaussmf(x_Bodentemperatur_range, 0.5, 0.08)
x_Bodentemperatur['HTB'] = fuzz.gaussmf(x_Bodentemperatur_range, 0.75, 0.08)
x_Bodentemperatur['SHTB'] = fuzz.gaussmf(x_Bodentemperatur_range, 1, 0.08)
y_Bewaesserungszeit['Nichts'] = fuzz.trimf(y_Bewaesserungszeit_range, [0, 0, 0.2])
y_Bewaesserungszeit['NZ'] = fuzz.trimf(y_Bewaesserungszeit_range, [0.05, 0.25, 0.45])
y_Bewaesserungszeit['MZ'] = fuzz.trimf(y_Bewaesserungszeit_range, [0.3, 0.5, 0.7])
y_Bewaesserungszeit['HZ'] = fuzz.trimf(y_Bewaesserungszeit_range, [0.55, 0.75, 0.95])
y_Bewaesserungszeit['SHZ'] = fuzz.trimf(y_Bewaesserungszeit_range, [0.8, 1, 1])

# Set the method of defuzzification
y_Bewaesserungszeit.defuzzify_method = 'centroid'

rule1 = ctrl.Rule(x_Bodenfeuchtigkeit['Nichts'] & x_Bodentemperatur['SHTB'], y_Bewaesserungszeit['SHZ'])
rule2 = ctrl.Rule(x_Bodenfeuchtigkeit['Nichts'] & x_Bodentemperatur['HTB'], y_Bewaesserungszeit['SHZ'])
rule3 = ctrl.Rule(x_Bodenfeuchtigkeit['Nichts'] & x_Bodentemperatur['MTB'], y_Bewaesserungszeit['HZ'])
rule4 = ctrl.Rule(x_Bodenfeuchtigkeit['Nichts'] & x_Bodentemperatur['NTB'], y_Bewaesserungszeit['HZ'])
rule5 = ctrl.Rule(x_Bodenfeuchtigkeit['Nichts'] & x_Bodentemperatur['Nichts'], y_Bewaesserungszeit['MZ'])
rule6 = ctrl.Rule(x_Bodenfeuchtigkeit['NB'] & x_Bodentemperatur['SHTB'], y_Bewaesserungszeit['SHZ'])
rule7 = ctrl.Rule(x_Bodenfeuchtigkeit['NB'] & x_Bodentemperatur['HTB'], y_Bewaesserungszeit['HZ'])
rule8 = ctrl.Rule(x_Bodenfeuchtigkeit['NB'] & x_Bodentemperatur['MTB'], y_Bewaesserungszeit['MZ'])
rule9 = ctrl.Rule(x_Bodenfeuchtigkeit['NB'] & x_Bodentemperatur['NTB'], y_Bewaesserungszeit['MZ'])
rule10 = ctrl.Rule(x_Bodenfeuchtigkeit['NB'] & x_Bodentemperatur['Nichts'], y_Bewaesserungszeit['NZ'])
rule11 = ctrl.Rule(x_Bodenfeuchtigkeit['MB'] & x_Bodentemperatur['SHTB'], y_Bewaesserungszeit['HZ'])
rule12 = ctrl.Rule(x_Bodenfeuchtigkeit['MB'] & x_Bodentemperatur['HTB'], y_Bewaesserungszeit['MZ'])
rule13 = ctrl.Rule(x_Bodenfeuchtigkeit['MB'] & x_Bodentemperatur['MTB'], y_Bewaesserungszeit['MZ'])
rule14 = ctrl.Rule(x_Bodenfeuchtigkeit['MB'] & x_Bodentemperatur['NTB'], y_Bewaesserungszeit['NZ'])
rule15 = ctrl.Rule(x_Bodenfeuchtigkeit['MB'] & x_Bodentemperatur['Nichts'], y_Bewaesserungszeit['NZ'])
rule16 = ctrl.Rule(x_Bodenfeuchtigkeit['HB'] & x_Bodentemperatur['SHTB'], y_Bewaesserungszeit['MZ'])
rule17 = ctrl.Rule(x_Bodenfeuchtigkeit['HB'] & x_Bodentemperatur['HTB'], y_Bewaesserungszeit['NZ'])
rule18 = ctrl.Rule(x_Bodenfeuchtigkeit['HB'] & x_Bodentemperatur['MTB'], y_Bewaesserungszeit['NZ'])
rule19 = ctrl.Rule(x_Bodenfeuchtigkeit['HB'] & x_Bodentemperatur['NTB'], y_Bewaesserungszeit['NZ'])
rule20= ctrl.Rule(x_Bodenfeuchtigkeit['HB'] & x_Bodentemperatur['Nichts'], y_Bewaesserungszeit['Nichts'])
rule21 = ctrl.Rule(x_Bodenfeuchtigkeit['SHB'] & x_Bodentemperatur['SHTB'], y_Bewaesserungszeit['Nichts'])
rule22 = ctrl.Rule(x_Bodenfeuchtigkeit['SHB'] & x_Bodentemperatur['HTB'], y_Bewaesserungszeit['Nichts'])
rule23 = ctrl.Rule(x_Bodenfeuchtigkeit['SHB'] & x_Bodentemperatur['MTB'], y_Bewaesserungszeit['Nichts'])
rule24 = ctrl.Rule(x_Bodenfeuchtigkeit['SHB'] & x_Bodentemperatur['NTB'], y_Bewaesserungszeit['Nichts'])
rule25 = ctrl.Rule(x_Bodenfeuchtigkeit['SHB'] & x_Bodentemperatur['Nichts'], y_Bewaesserungszeit['Nichts'])

rules = []
for i in range(1, 26):
    rules.append(eval("rule" + str(i)))

# Initialization
system = ctrl.ControlSystem(rules)
sim = ctrl.ControlSystemSimulation(system)

# Import the value of variables
sim.input['Bodenfeuchtigkeit'] = 0.2
sim.input['Bodentemperatur'] = 0.7
sim.compute()
output_Bewaesserungszeit = sim.output['Bewaesserungszeit']

print(output_Bewaesserungszeit)

What is wrong with my code? Thanks for your help sincerely.

**Comment by JDWarner** [comment]
Thank you for providing example code.  If you could also please provide a full traceback from the error encountered it would be helpful.

**Comment by xysh0826** [comment]
Thanks very much for your reply. And this is the bug. I have changed the rules but it still doesn't work.
















At 2020-07-18 01:06:17, "Josh Warner" <notifications@github.com> wrote:

Thank you for providing example code. If you could also please provide a full traceback from the error encountered it would be helpful.

**Comment by xysh0826** [comment]
This is the traceback from the error.
![bug](https://user-images.githubusercontent.com/68421130/87813958-31244700-c863-11ea-9f39-bbece6ad0608.PNG)

**Comment by JDWarner** [comment]
The error is informative.

You have three Antecedents, but only provided input values for two of them.  The output cannot be calculated.
