### ISSUE TITLE
Help with custom membership functions

### ISSUE THREAD

**Issue by snehalvartak** [scikit-fuzzy/scikit-fuzzy#278]
I am new to Fuzzylogic and trying to figure out if the skfuzzy package is something we can use for our project. Is there a way to define custom membership functions using the skfuzzy package? In the Tipping problem example there was a comment that says -
```
# Custom membership functions can be built interactively with a familiar,
# Pythonic API
```

What API is being referred here and how can I utilize it?

Thank you

**Comment by rlucasfm** [comment]
The API it says is related to the functions skfuzzy offers so you can use to define your membership functions. You can define membership functions using numpy arrays (mapping one value between 0 and 1 in the entire antecedent universe), and the lib functions as well, example: automf, trimf, sigmf, gaussmf, all that documented on the [skfuzzy docs](https://pythonhosted.org/scikit-fuzzy/api/api.html).

**Comment by rlucasfm** [comment]
Using the gaussmf to creating a gaussian shaped membership function can be as easy as:
```python
# Just giving you some context...
import skfuzzy as fuzz
from skfuzzy import control as ctrl

ant = ctrl.Antecedent(np.arange(0, 11, 1), 'antecedent')
cons = ctrl.Consequent(np.arange(0, 101, 1), 'consequent')

# The part you wanna know
cons['yes'] = fuzz.gaussmf(cons.universe, 50, 15)
```

**Comment by JDWarner** [comment]
Thanks @rlucasfm - @snehalvartak you can use *any* monotonic increasing rank-1 NumPy array to define the universe, then *any* NumPy array of same shape with values between 0 and 1 will be accepted as a fuzzy membership function defined on that universe.

Some convenient helper functions are provided but the sky is truly the limit.  If you can define it in NumPy as above, it will work.

See also the sparsity comment and example on #284 for using sparsity in these definitions to optimize complex system performance.
