### ISSUE TITLE
Need info about The meaning of triangles color in the result of Tipping Problem

### ISSUE THREAD

**Issue by bayan-kabbani** [scikit-fuzzy/scikit-fuzzy#283]
please I have a question in the figure why the triangle of both low and high is colored when the result is for example is 14.5%? 
Is that righ? the low and high is colored? Isn't it more correct low and medium is colored? 
sorry but I miss understanding the mean of coloring the result... any help
![q](https://user-images.githubusercontent.com/84635505/136989900-796a4d9c-03e3-4dea-a9e2-96fde790de4f.PNG)

**Comment by bayan-kabbani** [comment]
@Josh Warner

**Comment by TyBalduf** [comment]
This question was asked and answered on the [Computational Science Stack Exchange](https://scicomp.stackexchange.com/questions/40253/what-is-the-meaning-of-triangles-color-in-the-result-of-tipping-problem-in-sciki).

**Comment by JDWarner** [comment]
Thanks for the answer @TyBalduf - that linked answer is verified correct @bayan-kabbani.

**Comment by bayan-kabbani** [comment]
thanks @TyBalduf
