### ISSUE TITLE
Piecewise Linear Membership Function 

### ISSUE THREAD

**Issue by GStechschulte** [scikit-fuzzy/scikit-fuzzy#284]
Hello, when attempting to generate a piecewise membership using the package, it is not clear to me how the `piecemf` function is working. After having attempted to reverse engineer the source code, it is still unclear how to generate the following piecewise linear function:

I.e., in numpy it is intuitive of how to go about making the following piecewise function where from 0 to 2.5 the function is increasing with a slope of 0.4 given by the following degree of membership: 1 / 2.5. Then, the second constraint being any input x greater than 2.5 has an intercept of 1. In all, representing two linear functions. 

```
# In NumPy
stddev = np.arange(0, 4, 0.5)

np.piecewise(stddev, [stddev <= 0.5,  stddev <= 2.5, stddev > 2.5], 
                     [lambda stddev: 0*stddev, lambda stddev: 0.4*stddev, lambda stddev: 0*stddev + 1])
```

However, using the `piecemf` function, I can't seem to achieve these two linear functions with the constraints outlined in the `np.piecewise()` example above. Some guidance from the community would be appreciated.

**Comment by JDWarner** [comment]
@GStechschulte The function `piecemf` isn't designed or intended to be a general method to create _all_ piecewise membership functions.  It generates a specific kind of piecewise function (full piecewise math definition in the docstring) which is useful for FIRE filters.

Scikit-Fuzzy uses NumPy arrays for universes and membership so you are free to define your own membership functions however you like.  However, for your particular use case you can also use the function `trapmf` as 

``` python
# Define `stddev` as in your example
import skfuzzy as fuzz
fuzz.trapmf(stddev, [0, 2.5, 4, 4])
```

with equivalent output to your `np.piecewise` example.

However, you can do better than this (and you should).  **For any membership function with a linear region, you should only define the key endoints where there would be a change in derivative** and the intervening region will be interpolated with perfect accuracy at runtime.  This is faster and has a lower memory footprint which matters especially for complex systems.

So instead, consider this which is equivalent but more efficient
``` python
stddev = np.r_[0, 2.5, 3.5]  # Sparse! Only define at ends and key points
membership = np.r_[0, 1, 1]
```
from which it should be clear that you can trivially define any crazy piecewise (but continuous) membership function.  Discontinuous piecewise functions are also possible - they would define an anchor point and then that point +/- eps as needed in the sparse universe.
