### ISSUE TITLE
Any plan for a new release ?

### ISSUE THREAD

**Issue by yportier** [scikit-fuzzy/scikit-fuzzy#318]
The latest release 0.4.2 from 2019 is not compatible with Python 3.12 and PR #310 from 2023 seems to solve this problem, is there any plan for a new release ?

**Comment by xoolive** [comment]
Pushing this issue up, a release would be appreciated as CI breaks on 3.12 for tools using this library as a dependency

**Comment by dmvinson** [comment]
Agree, a new release would be great.

**Comment by JDWarner** [comment]
Imminent. Also apologies for the long delay.

**Comment by JDWarner** [comment]
@yportier @xoolive @dmvinson and @jcreinhold scikit-fuzzy 0.5.0 is now available on PyPi!

**Comment by dmvinson** [comment]
Thank you so much! Appreciate the followup
