### ISSUE TITLE
quesiton on operations missing last value

### ISSUE THREAD

**Issue by fabrizioruffini** [scikit-fuzzy/scikit-fuzzy#320]
Dear sirs, 
I was trying to use skfuzzy for some operations.
In my examples, I tried to perform an "and" and an "or" operations on two triangular functions. 
My question is: how come the last value of the second function (x=10) disappears after the operations, as in the image attached?

many thanks for your time

![fuzzy_logic](https://github.com/scikit-fuzzy/scikit-fuzzy/assets/23233825/1b750980-e875-454c-9661-5aee76bcf93e)

Here is my code, with scikit-fuzzy version '0.4.2'

# ------------------------------------------------------------------------------------------------------------------------

#!pip install -U scikit-fuzzy

%matplotlib inline
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

import matplotlib.pyplot as plt

delta = 0.001
start = 0
stop = 10 + delta
step = 0.25
x = np.arange(start, stop + delta, step)

# Triangular membership function
x1 = np.arange(0, 5 + delta, step)
trimf = fuzz.trimf(x1, [0, 2.5, 5])

# Triangular membership function
x2 = np.arange(2.5, 10 + delta, step)
trimf_2 = fuzz.trimf(x2, [2.5, 5, 10])

# fuzzy logic
tri_not = fuzz.fuzzy_not(trimf)
tri2_not = fuzz.fuzzy_not(trimf_2)
x3, tri_tri2_and = fuzz.fuzzy_and(x1, trimf, x2, trimf_2)
x4, tri_tri2_or  = fuzz.fuzzy_or(x1, trimf,  x2, trimf_2)
#print(x2)
#print(x3)

# Whole config
fig_scale = 1.5
plt.figure(figsize=(6.4 * fig_scale, 4.8 * fig_scale))
row = 4
col = 1

plt.subplot(row, col, 1)
plt.title("Fuzzy Logic")
plt.plot(x1, trimf, label="Triangle", marker=".")
plt.plot(x2, trimf_2, label="Triangle 2", marker=".")
plt.xlim([-1,11])
plt.legend(loc="upper right")

plt.subplot(row, col, 2)
plt.plot(x1, tri_not, label="Fuzzy NOT Triangle", marker="x")
plt.plot(x2, tri2_not, label="Fuzzy NOT Triangle 2", marker="x")
plt.grid()
plt.xlim([-1,11])
plt.legend(loc="upper right")

plt.subplot(row, col, 3)
plt.plot(x1, trimf, label="Triangle", marker=".", linestyle='--')
plt.plot(x2, trimf_2, label="Triangle 2", marker=".", linestyle='--')
plt.plot(x3, tri_tri2_and, label="Fuzzy AND", marker="^", color='purple')
plt.legend(loc="upper right");
plt.grid()
plt.ylim([0,1.1])
plt.xlim([-1,11])

plt.subplot(row, col, 4)
plt.plot(x1, trimf, label="Triangle", marker=".", linestyle='--')
plt.plot(x2, trimf_2, label="Triangle 2", marker=".", linestyle='--')
plt.plot(x4, tri_tri2_or, label="Fuzzy OR", marker="v", color='black')
plt.legend(loc="upper right");
plt.grid()
plt.ylim([0,1.1])
plt.xlim([-1,11]);

**Comment by JDWarner** [comment]
Thank you for this report @fabrizioruffini - I apologize for the delay. You are correct, this is a bug (and one with the lifetime of the package, likely originating in the translation of Hal Ottesen's original Matlab source).

Occasionally, depending on floating point error, the method for creating the union of the fuzzy universes in `_resampleuniverse` would exclude the final point.

**Comment by JDWarner** [comment]
For posterity I verified that this should not affect any system using the `skfuzzy.control` API, only trivial/example systems operating directly with basic functions in the original API as in the provided example.
