### ISSUE TITLE
Implementation of alpha cuts

### ISSUE THREAD

**Issue by pbreach** [scikit-fuzzy/scikit-fuzzy#48]
Within this package is there a way to perform alpha cuts on a given membership function? I.e. a way to get the bounds of the universe x that occur at the intersection of the membership function for a given degree of membership?

I've been exploring the package but can't seem to find anything. Hoping to integrate some of the work done here into some optimization algorithms elsewhere.

**Comment by JDWarner** [comment]
Hi @pbreach, I believe the functionality you are asking for is under `skfuzzy.lambda_cut`. This function returns an array of the same shape as the input membership function containing binary yes/no answering if each value was greater than the floating point value `lambdacut`. 

Extracting the bounds from that result just requires grabbing the first and last 1s.

**Comment by JDWarner** [comment]
(I just couldn't leave well enough alone, so I whipped up a function to do this myself. Look for it tomorrow)

**Comment by pbreach** [comment]
@JDWarner Thanks! I realized shortly after posting to use lambda cuts in the way you mentioned (still a bit new to the concept let alone the module), but I think it would be useful to have an alpha cut function that could do the interpolation. 

Unfortunately I won't be able to work on a PR at this time, but I may need to use the module again in the coming months. If so then I look forward to contributing.

**Comment by JDWarner** [comment]
@pbreach can you explain what you mean by alpha-cuts? Is it a different process than what I've called lambda-cuts, or is the difference essentially just getting the boundaries?

I have a working local version which does calculate the exact boundaries. Also found and fixed an edge case error in `skfuzzy.lambda_cut` - it was not working as expected for a cut value of 1.0.

**Comment by pbreach** [comment]
Yes it is essentially the boundaries of a lambda cut for a given alpha level (or cut value) on the interval of [0,1].

For example, in the case of a sigmoidal membership function, alpha cut values in the set of (0,1) will give only one value, while alpha cut values of 0 and 1 should give two values corresponding to the bounds where the membership function is 0 and 1 respectively.

**Comment by pbreach** [comment]
After looking into this more it looks like alpha cuts and lambda cuts actually may be analogous... Alpha cut refers to the interval [a_alpha, b_alpha] for a particular alpha level or degree of membership.

I think the `lambda_cut_boundaries` function with a way to interpolate is exactly what I was referring to originally.

**Comment by JDWarner** [comment]
Closed by #50 (see discussion and implementation in that PR)
