### ISSUE TITLE
Any possibility for surface plotting as in Matlab?

### ISSUE THREAD

**Issue by ngoonee** [scikit-fuzzy/scikit-fuzzy#65]
Wondering whether there's any plans in this direction as I have not been able to find anything from searching around (or by introspection on the code). Would love to be proven wrong.

Otherwise, hacking together something along the lines of 'given this range of possible inputs, get defuzzified outputs for all of them and produce something plottable' should not be too hard. I wouldn't want to start trying unless its not already available though.

**Comment by JDWarner** [comment]
@ngoonee what you've found is correct, I believe. There isn't (yet!) a defined function or interface specifically crafted to visualize a fuzzy surface.

That said, all of the base tools are present and I definitely would like to see this exposed in the package. I have _considered_ making a much more elegant class-based interface for fuzzy systems which would carry enough information to automatic generate such plots. However, other commitments have kept me from working on it, so you wouldn't be stepping on toes.

If you would like to work on this, it would be much appreciated! I'd be happy to advise/assist.

**Comment by JDWarner** [comment]
@ngoonee With the new features now available in #70 as a WIP, I believe plotting control surfaces is entirely possible.

If you have solved examples of this, please point them my way and advise regarding where/how you would like them to be exposed. 

I'm closing this Issue - let's take the discussion to #70.
