### ISSUE TITLE
Addition of multiple rules

### ISSUE THREAD

**Issue by coolkaku** [scikit-fuzzy/scikit-fuzzy#67]
I have 64 fuzzy If-Then rules to add in my fuzzy inference system but I am unable to add more than 2 rules especially the rules with the same consequent cannot be added together. Please help

**Comment by JDWarner** [comment]
Applying fuzzy rules have a number of important yet subtle points which are often missed. Combining rules must be done as shown in [the tipping problem example](http://pythonhosted.org/scikit-fuzzy/auto_examples/plot_tipping_problem.html). Read that example carefully - it can be generalized to an arbitrarily large system. It gets unwieldy but it is possible. I'm working on a more elegant higher level interface, bit it's all possible now.

My guess is you're using a different approach which results in lost information or a units mismatch in universe variables, but I can't say for sure without knowing more.

**Comment by JDWarner** [comment]
Also, using max/min inference in the case of several rules with the same consequent variable and membership function, during rule aggregation you simply compare and take the highest (max) value.

**Comment by JDWarner** [comment]
Closing this issue, but feel free to reopen if you feel it isn't resolved.
