### ISSUE TITLE
Fuzzy Logic Design

### ISSUE THREAD

**Issue by mohammedaljawad** [scikit-fuzzy/scikit-fuzzy#69]
Dear All, 
Firstly, I'd like to express my gratitude to Dr.Josh for his efforts of building this API and for his cooperation by answering our questions. Secondly, I am facing problem in the fuzzy design. I am just wondering whether this definition of the output membership function is right or not:

trust_hi = fuzz.trimf(x_trust, [0, 0, 0.25])
trust_mh = fuzz.trimf(x_trust, [0,0.25,0.5])
trust_md = fuzz.trimf(x_trust, [0.25,0.5,0.75])
trust_ml = fuzz.trimf(x_trust, [0.5,0.75, 1])
trust_lo = fuzz.trimf(x_trust, [0.75, 1, 1])
![output](https://cloud.githubusercontent.com/assets/15655076/11242096/800f474e-8df7-11e5-96d2-8471b620af19.jpg)

Regards 
Mohammed

**Comment by JDWarner** [comment]
Hi @mohammedaljawad - that looks correct, except that your variable naming appears to be reversed from what's shown in the figure (low <-> high).

You may find the new fuzzy control system API in #70 of interest.

**Comment by JDWarner** [comment]
Closing as the question at hand is addressed. Feel free to continue the discussion regarding design problems/advice on the mailing list.
