### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by OrkoHunter** [scikit-fuzzy/scikit-fuzzy#71]
Hi! Is there any documentation page yet? I was unable to find it in the README file.

If not, then setting up a hook on [readthedocs.org](https://readthedocs.org/) would be a cool idea.

**Comment by JDWarner** [comment]
The project docs are online at http://pythonhosted.org/scikit-fuzzy but aren't linked as well as they could be.

Improvements welcome!

**Comment by OrkoHunter** [comment]
Tried to fix in #72
