### ISSUE TITLE
Test coverage for `skfuzzy.control` module

### ISSUE THREAD

**Issue by JDWarner** [scikit-fuzzy/scikit-fuzzy#73]
For the new control system API first introduced in #70, a set of unit tests should be added which will fully cover the module.

**Comment by nilayrox18** [comment]
Sir i am facing a problem at
tipping.input['quality'] = 6.5

it is taking ]'quality'] as a index what should i do??

**Comment by JDWarner** [comment]
There is still room for improvement, but test coverage was greatly enhanced in #108. Closing for now.
