### ISSUE TITLE
Improve control module documenation

### ISSUE THREAD

**Issue by jsexauer** [scikit-fuzzy/scikit-fuzzy#77]
- Several docstrings are missing from the new classes I added
- Improve PythonHosted documentation to include a fuzzy control primer and tipping problem example using the control module (I have this mostly written already) -- Probably shouldn't be done until the API is in a bit more stable condition

**Comment by mrandrewandrade** [comment]
I would like to help improve the documentation and help with a fuzzy control primer and other examples!
@JDWarner  I have been working on a fuzzy control system for fan control of a battery system.  Do you have some source code for that air conditioning example in your PyCon presentation?  I think it would be a great example of using fuzzy control for extremely non linear systems.

**Comment by JDWarner** [comment]
@mrandrewandrade That specific example was hypothetical but based on real-world experience. Making a fan control should be relatively simple, so long as you have good inputs, but as in most things the devil is in the details. You'll probably need to iterate a bit to figure out reasonable values, but it shouldn't take too much experimentation.

**Comment by mrandrewandrade** [comment]
No problem, I will try and write up the example we are using.  Just wanted to compare our solution methodology with an already implemented solution (if that existed) since I am fairly new to fuzzy logic

**Comment by JDWarner** [comment]
@mrandrewandrade additional examples are always welcome! I'm closing this Issue for now, but there are definitely places in the new API `skfuzzy.control` which could use docstrings or could be expanded.
