### ISSUE TITLE
Microsoft Visual C++ 2010 erro

### ISSUE THREAD

**Issue by nilayrox18** [scikit-fuzzy/scikit-fuzzy#99]
hello sir first of all thank you for you quick and effective response with your help i am able to complete my robot. i am facing some other issue like Microsoft Visual C++ 2010 is missing and error for vcvarsall.bat is not found. please it is resist me from installing many other modules please reply with some permanent solution. thank yoou

**Comment by JDWarner** [comment]
This isn't a scikit-fuzzy problem, it's your environment. scikit-fuzzy is pure Python. Nothing in this package would trigger that error.

If you must use Windows, much of the scientific Python stack is extremely difficult to build without a carefully constructed and maintained compilation environment. It's an awful mess trying to go this alone. My strongest recommendation is to use a pre-built and maintained environment, the two front runners being Anaconda from Continuum or Canopy from Enthought.

Pick one, and use it. These will maintain all of your Python packages, keep them up to date, and on Windows ship you compiled versions of everything which needs to be compiled. No need for MS Visual C++.

Once a usable Windows Python environment is installed, update it, then reinstall scikit-fuzzy with `python setup.py develop`. 

An even more durable solution is to switch to _any other operating system_ than Windows. OSX, Linux (or any *NIX), and BSD all ship with robust compilation toolchains. Ergo, it is possible to develop Cython etc. on those platform without jumping through ridiculous hoops. But for this package specifically, you don't need a compiler - just the supporting framework.
